# Generated by Django 5.1.1 on 2024-10-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Определяет порядок лекций в курсе', null=True, verbose_name='Порядок лекции'),
        ),
    ]
